const Posts = [
    {
      post_id: 1,
      post_caption: 'Beautiful Sunset!',
      media_url: 'https://example.com/media/sunset.jpg',
      user_id: 1,
      created_at: '2024-08-07T18:30:00.000Z',
      isHidden: false,
    },
    {
      post_id: 2,
      post_caption: 'Check out this new recipe!',
      media_url: 'https://example.com/media/recipe.jpg',
      user_id: 2,
      created_at: '2024-08-06T16:20:00.000Z',
      isHidden: false,
    },
    {
      post_id: 3,
      post_caption: 'My recent trip to the mountains!',
      media_url: 'https://example.com/media/mountains.jpg',
      user_id: 3,
      created_at: '2024-08-08T09:15:00.000Z',
      isHidden: false,
    },
    {
      post_id: 4,
      post_caption: 'Amazing artwork I just completed.',
      media_url: 'https://example.com/media/artwork.jpg',
      user_id: 4,
      created_at: '2024-08-05T14:50:00.000Z',
      isHidden: true,
    },
    {
      post_id: 5,
      post_caption: 'New blog post about AI advancements.',
      media_url: 'https://example.com/media/blog.jpg',
      user_id: 5,
      created_at: '2024-08-07T11:30:00.000Z',
      isHidden: false,
    },
    {
      post_id: 6,
      post_caption: 'Exploring the city lights.',
      media_url: 'https://example.com/media/citylights.jpg',
      user_id: 6,
      created_at: '2024-08-07T20:45:00.000Z',
      isHidden: false,
    },
    {
      post_id: 7,
      post_caption: 'Delicious breakfast!',
      media_url: 'https://example.com/media/breakfast.jpg',
      user_id: 7,
      created_at: '2024-08-07T07:10:00.000Z',
      isHidden: false,
    },
    {
      post_id: 8,
      post_caption: 'My pet’s cute moments.',
      media_url: 'https://example.com/media/pet.jpg',
      user_id: 8,
      created_at: '2024-08-06T10:30:00.000Z',
      isHidden: false,
    },
    {
      post_id: 9,
      post_caption: 'Nature at its best.',
      media_url: 'https://example.com/media/nature.jpg',
      user_id: 9,
      created_at: '2024-08-05T16:40:00.000Z',
      isHidden: false,
    },
    {
      post_id: 10,
      post_caption: 'Workout routine updates.',
      media_url: 'https://example.com/media/workout.jpg',
      user_id: 10,
      created_at: '2024-08-08T08:45:00.000Z',
      isHidden: false,
    },
    {
      post_id: 11,
      post_caption: 'Gaming highlights.',
      media_url: 'https://example.com/media/gaming.jpg',
      user_id: 11,
      created_at: '2024-08-07T14:30:00.000Z',
      isHidden: false,
    },
    {
      post_id: 12,
      post_caption: 'DIY project completed!',
      media_url: 'https://example.com/media/diy.jpg',
      user_id: 12,
      created_at: '2024-08-06T19:20:00.000Z',
      isHidden: true,
    },
    {
      post_id: 13,
      post_caption: 'Evening walk in the park.',
      media_url: 'https://example.com/media/park.jpg',
      user_id: 13,
      created_at: '2024-08-08T18:50:00.000Z',
      isHidden: false,
    },
    {
      post_id: 14,
      post_caption: 'Sunrise over the beach.',
      media_url: 'https://example.com/media/beach.jpg',
      user_id: 14,
      created_at: '2024-08-07T06:30:00.000Z',
      isHidden: false,
    },
    {
      post_id: 15,
      post_caption: 'Favorite book recommendation.',
      media_url: 'https://example.com/media/book.jpg',
      user_id: 15,
      created_at: '2024-08-07T16:00:00.000Z',
      isHidden: false,
    },
    {
      post_id: 16,
      post_caption: 'Mountain biking adventure!',
      media_url: 'https://example.com/media/bike.jpg',
      user_id: 16,
      created_at: '2024-08-05T12:15:00.000Z',
      isHidden: false,
    },
    {
      post_id: 17,
      post_caption: 'Family gathering photos.',
      media_url: 'https://example.com/media/family.jpg',
      user_id: 17,
      created_at: '2024-08-08T20:30:00.000Z',
      isHidden: false,
    },
    {
      post_id: 18,
      post_caption: 'New tech gadgets!',
      media_url: 'https://example.com/media/gadgets.jpg',
      user_id: 18,
      created_at: '2024-08-06T09:40:00.000Z',
      isHidden: true,
    },
    {
      post_id: 19,
      post_caption: 'Street art appreciation.',
      media_url: 'https://example.com/media/streetart.jpg',
      user_id: 19,
      created_at: '2024-08-08T15:50:00.000Z',
      isHidden: false,
    },
    {
      post_id: 20,
      post_caption: 'Camping under the stars.',
      media_url: 'https://example.com/media/camping.jpg',
      user_id: 20,
      created_at: '2024-08-06T22:45:00.000Z',
      isHidden: false,
    },
    {
      post_id: 21,
      post_caption: 'Music concert memories.',
      media_url: 'https://example.com/media/concert.jpg',
      user_id: 21,
      created_at: '2024-08-07T11:30:00.000Z',
      isHidden: false,
    },
    {
      post_id: 22,
      post_caption: 'Coffee art from this morning.',
      media_url: 'https://example.com/media/coffee.jpg',
      user_id: 22,
      created_at: '2024-08-08T08:15:00.000Z',
      isHidden: false,
    },
    {
      post_id: 23,
      post_caption: 'Road trip to the countryside.',
      media_url: 'https://example.com/media/roadtrip.jpg',
      user_id: 23,
      created_at: '2024-08-05T17:45:00.000Z',
      isHidden: true,
    },
    {
      post_id: 24,
      post_caption: 'Cooking experiment gone right!',
      media_url: 'https://example.com/media/cooking.jpg',
      user_id: 24,
      created_at: '2024-08-07T18:10:00.000Z',
      isHidden: false,
    },
    {
      post_id: 25,
      post_caption: 'Exploring the great outdoors.',
      media_url: 'https://example.com/media/outdoors.jpg',
      user_id: 25,
      created_at: '2024-08-08T14:00:00.000Z',
      isHidden: false,
    },
    {
      post_id: 26,
      post_caption: 'Vintage car show!',
      media_url: 'https://example.com/media/vintagecar.jpg',
      user_id: 26,
      created_at: '2024-08-06T13:00:00.000Z',
      isHidden: false,
    },
    {
      post_id: 27,
      post_caption: 'Fun at the amusement park.',
      media_url: 'https://example.com/media/amusementpark.jpg',
      user_id: 27,
      created_at: '2024-08-08T19:30:00.000Z',
      isHidden: false,
    },
    {
      post_id: 28,
      post_caption: 'Photography tricks and tips.',
      media_url: 'https://example.com/media/photography.jpg',
      user_id: 28,
      created_at: '2024-08-07T15:20:00.000Z',
      isHidden: true,
    },
    {
      post_id: 29,
      post_caption: 'City skyline from the rooftop.',
      media_url: 'https://example.com/media/rooftop.jpg',
      user_id: 29,
      created_at: '2024-08-08T09:30:00.000Z',
      isHidden: false,
    },
    {
      post_id: 30,
      post_caption: 'Weekend getaway photos.',
      media_url: 'https://example.com/media/getaway.jpg',
      user_id: 30,
      created_at: '2024-08-08T11:50:00.000Z',
      isHidden: false,
    },
  ]

export default Posts